apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('', views.login_view, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('banners/', views.banners, name='banners'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
]

apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('list/', views.news_list, name='news_list'),
    path('public_comment/', views.public_comment, name='public_comment'),
]

apps/xfzauth/urls.py
from django.urls import path

from apps.xfzauth import views

app_name = 'xfzauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('cache_test/', views.cache_test, name='cache_test')
]

xiaofanzhuo/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('news/', include('apps.news.urls', namespace="news")),
    path('cms/', include('apps.cms.urls', namespace="cms")),
    path('account/', include('apps.xfzauth.urls', namespace="xfzauth")),
    path('course/', include('apps.course.urls', namespace="course")),
    path('ueditor/', include('apps.ueditor.urls', namespace="ueditor")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
from apps.forms import FormMixin
from django import forms

from apps.news.models import News


class EditNewsCategoryForm(forms.Form, FormMixin):
    pk = forms.IntegerField(error_messages={'required': "必须传入分类的id"})
    name = forms.CharField(max_length=100)


class WriteNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']

apps/cms/views.py
from datetime import datetime

from django.core.paginator import Paginator
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.timezone import make_aware
from django.views.decorators.http import require_POST, require_GET
from urllib import parse

# Create your views here.
from django.views.generic import View

from apps.cms.forms import EditNewsCategoryForm, WriteNewsForm
from apps.news.models import NewsCategory, News
from utils import restful
import os
from django.conf import settings


@staff_member_required(login_url='index')
def login_view(request):
    return render(request, 'cms/index.html')


class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.create(title=title, desc=desc, thumbnail=thumbnail, content=content, category=category,
                                author=request.user)
            return restful.ok()
        else:
            print(form.get_error())
            return restful.params_error(message=form.get_error())


@require_GET
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'cms/news_category.html', context=context)


@require_POST
def add_news_category(request):
    name = request.POST.get('name')

    exists = NewsCategory.objects.filter(name=name)
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已存在')


def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='该分类不存在')
    else:
        return restful.params_error(message=form.get_error())


@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.params_error(message='该分类不存在')


def banners(request):
    return render(request, 'cms/banners.html')


@require_POST
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.result(data={'url': url})


def news_list(request):
    context = {
        'categories': NewsCategory.objects.all(),
        'newses': News.objects.select_related('category', 'author').all()
    }
    return render(request, 'cms/news_list.html', context=context)


class NewsListView(View):
    def get(self, request):
        # request.GET：获取出来的所有数据，都是字符串类型
        page = int(request.GET.get('p',1))
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category', 0) or 0)
        # request.GET.get(参数,默认值)
        # 这个默认值是只有这个参数没有传递的时候才会使用
        # 如果传递了，但是是一个空的字符串，那么也不会使用默认值
        newses = News.objects.select_related('category', 'author')

        if start or end:
            if start:
                start_date = datetime.strptime(start, '%Y/%m/%d')
            else:
                start_date = datetime(year=2018, month=6, day=1)
            if end:
                end_date = datetime.strptime(end, '%Y/%m/%d')
            else:
                end_date = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))

        if title:
            newses = newses.filter(title__icontains=title)

        if category_id:
            newses = newses.filter(category=category_id)
        paginator = Paginator(newses, 1)
        page_obj = paginator.page(page)
        context_data = self.get_pagination_data(paginator, page_obj)
        context = {
            'categories': NewsCategory.objects.all(),
            'newses': page_obj.object_list,
            'paginator': paginator,
            'page_obj': page_obj,
            'start': start,
            'end': end,
            'title': title,
            'category_id': category_id,
            'url_query': '&' + parse.urlencode({
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or ''
            })
        }
        context.update(context_data)
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=1):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page + 1, num_pages + 1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

        return {
            # left_pages：代表的是当前这页的左边的页的页码
            'left_pages': left_pages,
            # right_pages：代表的是当前这页的右边的页的页码
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages
        }

front/templates/cms/banners.html
{% extends 'cms/base.html' %}

{% block title %}
    轮播图管理
{% endblock %}

{% block head %}
    <style>
        .btn-group {
            float: left;
        }

        .tips {
            float: left;
        }

        .banner-item {
            width: 800px;
        }

        .thumbnail-group {
            float: left;
            width: 230px;
        }

        .thumbnail-group .thumbnail {
            width: 100%;
        }

        .more-group {
            float: left;
            margin-left: 20px;
            width: 500px;
        }
    </style>
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/banners.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <b style="size: A3">轮播图管理</b>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group">
                <button class="btn btn-primary" id="add-banner-btn">
                    <i class="fa fa-plus"></i>
                    添加轮播图
                </button>
            </div>
            <ul class="tips">
                <li>支持JPG,GIF,PNG格式，最多可上传6张</li>
                <li>比例4:1，宽度在800px以上，5M以内</li>
            </ul>
        </div>
    </div>
    <div class="banner-list-group"></div>
    <script id="banner-item" type="text/html">
        {% verbatim %}
        <div class="box banner-item">
            <div class="box-header">
                <span>优先级：0</span>
                <button class="btn btn-default btn-xs pull-right">
                    <i class="fa fa-close"></i>
                </button>
            </div>
            <div class="box-body">
                <div class="thumbnail-group">
                    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1587438838070&di=259bd85b4663f50e7db798d8ac19b493&imgtype=0&src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20190830%2Ff9f5efbcfdad48fcac16cdd90d42c488.jpeg"
                         alt="" class="thumbnail">
                </div>
                <div class="more-group">
                    <div class="form-group">
                        <input type="number" class="form-control" name="position">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="link_to">
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button class="btn btn-primary pull-right">保存</button>
            </div>
        </div>
        {% endverbatim %}
    </script>
{% endblock %}

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}

    {% endblock %}|小饭桌管理系统</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    {#  <link rel="stylesheet" href="bower_components/Ionicons/css/ionicons.min.css">#}
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <!-- Morris chart -->
    {#  <link rel="stylesheet" href="bower_components/morris.js/morris.css">#}
    <!-- jvectormap -->
    {#  <link rel="stylesheet" href="bower_components/jvectormap/jquery-jvectormap.css">#}
    <!-- Date Picker -->
    {#  <link rel="stylesheet" href="bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">#}
    <!-- Daterange picker -->
    {#  <link rel="stylesheet" href="bower_components/bootstrap-daterangepicker/daterangepicker.css">#}
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
{#  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>#}
{#  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>#}
  <![endif]-->

    <!-- Google Font -->
    {#  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">#}

    <!-- jQuery 3 -->
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'adminlte/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    {#    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->#}
    {#    <script src="{% static 'adminlte/dist/js/pages/dashboard.js' %}"></script>#}
    <!-- AdminLTE for demo purposes -->
    {#<script src="dist/js/demo.js"></script>#}

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/myajax.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    {% block head %}

    {% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>小饭桌后台管理系统</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static 'images/任务安排.png' %}" class="user-image" alt="User Image">
                            <span class="hidden-xs">Homer</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{% static 'images/任务安排.png' %}" class="img-circle" alt="User Image">

                                <p>
                                    Homer
                                    <small>最屌的工程师</small>
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登陆</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li>
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                <li class="header">新闻管理</li>
                <li>
                    <a href="{% url 'cms:news_list' %}">
                        <i class="fa fa-home"></i>
                        <span>新闻列表</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:write_news' %}">
                        <i class="fa fa-edit"></i>
                        <span>发布新闻</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:news_category' %}">
                        <i class="fa fa-tag"></i>
                        <span>新闻分类</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cms:banners' %}">
                        <i class="fa fa-window-restore"></i>
                        <span>轮播图</span>
                    </a>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            {% block content-header %}

            {% endblock %}
        </section>

        <!-- Main content -->
        <section class="content">
            {% block content %}

            {% endblock %}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <b>小饭桌后台管理系统</b>
    </footer>

    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->


</body>
</html>

front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#">小不点管理系统</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">想用你的美味吧</p>

    <form action="{% url 'xfzauth:login' %}" method="post">
        {% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="手机号码" name="telephone">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="密码" name="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox" name="remember" value="1"> 记住我
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登陆</button>
        </div>
        <!-- /.col -->
      </div>
    </form>



    <a href="#">忘记密码</a><br>
    <a href="register.html" class="text-center">注册新用户</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'adminlte/plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

front/templates/cms/news_list.html
{% extends 'cms/base.html' %}
{% load news_filters %}


{% block title %}
    新闻列表
{% endblock %}

{% block head %}
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>
    <style>
        .left-group {
            margin-right: 20px;
        }
    </style>
{% endblock %}

{% block content-header %}

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <form action="" method="get" class="form-inline">
                        <div class="form-group left-group">
                            <label for="">时间：</label>
                            {% if start %}
                                <input type="text" class="form-control" name="start" placeholder="起始时间"
                                       id="start-picker" readonly value="{{ start }}">
                            {% else %}
                                <input type="text" class="form-control" name="start" placeholder="起始时间"
                                       id="start-picker" readonly>
                            {% endif %}
                            <span>—</span>
                            {% if end %}
                                <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间"
                                       readonly value="{{ end }}">
                            {% else %}
                                <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间"
                                       readonly>
                            {% endif %}
                        </div>
                        <div class="form-group left-group">
                            <label for="title-input">标题：</label>
                            {% if title %}
                                <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字"
                                       value="{{ title }}">
                            {% else %}
                                <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字">
                            {% endif %}
                        </div>
                        <div class="form-group left-group">
                            <label for="category-input">分类：</label>
                            <select name="category" id="" class="form-control">
                                {% if category_id == 0 %}
                                    <option value="0" selected>所有分类</option>
                                {% else %}
                                    <option value="0">所有分类</option>
                                {% endif %}
                                {% for category in categories %}
                                    {% if category_id == category.pk %}
                                        <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                                    {% else %}
                                        <option value="{{ category.pk }}">{{ category.name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group left-group">
                            <button class="btn btn-primary">查询</button>
                        </div>
                        <div class="form-group">
                            <a href="{% url 'cms:news_list' %}">清除查询</a>
                        </div>
                    </form>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>标题</th>
                            <th>分类</th>
                            <th>发布时间</th>
                            <th>作者</th>
                            <th>操作</th>
                        </tr>
                        <tbody>
                        {% for news in newses %}
                            <tr>
                                <td><a href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a></td>
                                <td>{{ news.category.name }}</td>
                                <td>{{ news.pub_time|time_format }}</td>
                                <td>{{ news.author.username }}</td>
                                <td>
                                    <a href="#" class="btn btn-info btn-xs">编辑</a>
                                    <button class="btn btn-danger btn-xs">删除</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        </thead>
                    </table>
                </div>
                <div class="box-footer">
                    <p class="pull-left">第{{ current_page }}/总共{{ num_pages }}页</p>
                    <ul class="pagination pull-right">
                        {#上一页#}
                        {% if page_obj.has_previous %}
                            <li><a href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                        {% else %}
                            <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                        {% endif %}

                        {# 是否需要出现三个点 #}
                        {% if left_has_more %}
                            <li><a href="?p=1">1</a></li>
                            <li><a href="javascript:void(0);">...</a></li>
                        {% endif %}

                        {# 左边的页码 #}
                        {% for left_page in left_pages %}
                            <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                        {% endfor %}

                        {# 当前的页面 #}
                        <li class="active"><a href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                        {# 右边的页码 #}
                        {% for right_page in right_pages %}
                            <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                        {% endfor %}

                        {# 用来控制右边三个点 #}
                        {% if right_has_more %}
                            <li><a href="javascript:void(0);">...</a></li>
                            <li><a href="?p={{ num_pages }}{{ url_query }}">{{ num_pages }}</a></li>
                        {% endif %}

                        {#下一页#}
                        {% if page_obj.has_next %}
                            <li><a href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                        {% else %}
                            <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}