apps/xfzauth/urls.py
from django.urls import path

from apps.xfzauth import views

app_name = 'xfzauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('cache_test/', views.cache_test, name='cache_test')
]

xiaofanzhuo/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('news/', include('apps.news.urls', namespace="news")),
    path('cms/', include('apps.cms.urls', namespace="cms")),
    path('account/', include('apps.xfzauth.urls', namespace="xfzauth")),
    path('course/', include('apps.course.urls', namespace="course")),
    path('ueditor/', include('apps.ueditor.urls', namespace="ueditor")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="homer">
    <meta name="keyword" content="HTML, CSS, XML, XHTML, JavaScript">
    <link rel="shortcut icon" href="{% static 'images/任务安排.png' %}">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1748588_rz7h4nfj23s.css">
    <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/myajax.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base/front_base.min.js' %}"></script>
    {% block head %}

    {% endblock %}
</head>
<body>
<header class="header">
    <div class="container">
        <div class="logo-box" title="Homer is a superman">
            <a href="/templates/news/index.html"></a>
        </div>

        <ul class="nav">
            <li class="active" tabindex="4"><a href="/">创业资讯</a></li>
            <li><a href="/" tabindex="2">创业课堂</a></li>
            <li><a href="/" tabindex="3">付费资讯</a></li>
            <li><a href="/" tabindex="1" style="color: #5c87d9">搜索</a></li>
        </ul>

        <div class="auth-box">
            <i class="iconfont icon-BusinessIcons_AccountPerson"></i>
            {% if user.is_authenticated %}
                <a href="#" class="authenticated-box">{{ user.username }}</a>
                <div class="user-more-box">
                    <i class="triangle"></i>
                    {% if user.is_staff %}
                        <a href="{% url 'cms:index' %}">管理系统</a>
                    {% endif %}
                    <a href="{% url 'xfzauth:logout' %}" class="menu_bar">退出登录</a>
                </div>
            {% else %}
                <a href="#" class="signin-btn">登陆</a> /
                <a href="#" class="signup-btn">注册</a>
            {% endif %}
        </div>


    </div>
</header>



{% block main %}

{% endblock %}

<footer class="footer">
    <div class="top-group">
        <div class="top-inner-group">
            <div class="logo-box"></div>
            <div class="detail-group">
                <div class="line1">
                    <ul class="links">
                        <li><a href="">关于小饭桌</a></li>
                        <li><a href="">创业课堂</a></li>
                        <li><a href="">寻求报道</a></li>
                        <li><a href="">创业礼包</a></li>
                    </ul>
                    <div class="about-us">
                        <span class="title">关于我们:</span>
                        <ul class="social-group">
                            <li class="weixin">
                                <a class="text" href="#">xfz08</a>
                                <div class="wx-qrcode"></div>
                            </li>
                            <li class="weibo"><a class="text" href="#">小饭桌创业课堂</a></li>
                        </ul>
                    </div>
                </div>
                <div class="line2">
                    <p class="address">地址：深圳市龙华区平湖街道上木古村岭根吓9号</p>
                    <p class="contact">联系方式：400-923-2313（工作日10点-18点）</p>
                </div>
            </div>
        </div>
    </div>

    <div class="bottom-group">
        ©2020 北京子木投资顾问有限公司 京ICP备15051289号 | 增值电信业务经营许可证：京B2-20170574
    </div>
</footer>

<div class="mask-wrapper">
    <div class="auth-wrapper">
        <div class="close-group">
            <span class="close-btn icon-close iconfont"></span>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-wrapper">
                <div class="signin-group auth-group">
                    <div class="top-group">
                        <span class="title">请登录</span>
                        <a href="javascript:void(0);" class="switch">立即注册></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" id="login_tel" class="form-control" name="telephone"
                                   placeholder="请输入手机号码">
                        </div>
                        <div class="input-group">
                            <input type="password" id="login_pwd" class="form-control" name="password"
                                   placeholder="请输入密码">
                        </div>
                        <div class="input-group">
                            <label class="remmenber-label">
                                <input type="checkbox" class="check-box" name="remember" value="1">
                                记住我
                            </label>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" value="立即登陆">
                        </div>
                    </div>
                </div>
                <div class="signup-group auth-group">
                    <div class="top-group">
                        <span class="title">请注册</span>
                        <a href="javascript:void(0);" class="switch">立即登陆></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control" name="username" placeholder="用户名">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" class="form-control" name="img_captcha" placeholder="请输入验证码">
                            </div>
                            <div class="input-group-addon">
                                <img src="{% url 'xfzauth:img_captcha' %}" class="img-captcha" alt="">
                            </div>
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password1" placeholder="密码">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password2" placeholder="确认密码">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                            </div>
                            <div class="input-group-addon">
                                <span class="sms-captcha-btn">发送短信验证码</span>
                            </div>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" value="立即注册" name="submit-btn">
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

</body>
</html>